# Generated by Django 2.0.5 on 2018-05-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flight',
            new_name='flight_id',
        ),
    ]
