# Generated by Django 2.0.5 on 2018-05-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_auto_20180507_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passenger',
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(to='airlines.Passenger'),
        ),
    ]
