# Generated by Django 2.0.5 on 2018-05-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0004_auto_20180508_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_num',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
