# Generated by Django 2.0.5 on 2018-05-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0005_auto_20180508_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentprovider',
            old_name='name',
            new_name='pay_provider_name',
        ),
        migrations.AddField(
            model_name='paymentprovider',
            name='pay_provider_id',
            field=models.CharField(default=1000, max_length=10),
            preserve_default=False,
        ),
    ]
