# Generated by Django 2.0.5 on 2018-05-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0006_auto_20180508_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='booking_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='booking_num',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
