# Generated by Django 2.0.5 on 2018-05-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0007_auto_20180508_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
